---
- name: OS specific Helm install
  ansible.builtin.import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Installing Helm
  ansible.builtin.import_role:
    name: install
  vars:
    install_packages:
      - helm=3.18.4-1
