# Ansible variables
ansible_python_interpreter: /usr/bin/python3

# Initial server setup
create_users:
  - name: admin
    # **NOTE**: Do not specify passwords directly in host_vars, use Ansible Vault
    # (https://docs.ansible.com/ansible/latest/vault_guide/vault.html) to store your secrets!
    password: "{{ admin_password }}"
    groups: sudo
  - name: serviceaccount
    shell: /usr/sbin/nologin
ssh_pub_files:
  - name: admin
    file: ~/.ssh/admin_id_rsa.pub

# Kubernetes variables
# Make sure node names are unique for easy identification of the node, if not specified inventory_hostname will be used as default
node_name: controller0
metallb_addresses:
  - 192.168.10.0/24
  - 192.168.9.1-192.168.9.5
  - fc00:f853:0ccd:e799::/124
