# Initial server setup (see: https://www.digitalocean.com/community/tutorials/initial-server-setup-with-ubuntu-22-04)
- name: Initial server setup
  user: root
  hosts: all
  # See vars/example_user_vault.yml on how to provide passwords for your users
  vars_files:
    - vars/user_vault.yml

  tasks:
  - name: Add the user and append to appropriate groups
    user:
      name: "{{ item.name }}"
      shell: "{{ item.shell | default('/bin/bash') }}"
      groups: "{{ item.groups | default('') }}"
      password: "{{ item.password }}"
      append: yes
    with_items: "{{ create_users | default([]) }}"
    no_log: true

  - name: Adding ssh keys to users authorized_keys
    authorized_key:
      user: "{{ item.name }}"
      key: "{{ lookup('file', item.file) }}"
    with_items: "{{ ssh_pub_files | default([]) }}"
