---
# **NOTE:** Make sure you have SSH keys set up, otherwise you will not be able to reconnect to the server after this play
- name: Disabling password authentication and empty passwords
  hosts: all

  tasks:
    - name: Disabling PasswordAuthentication
      ansible.builtin.replace:
        path: /etc/ssh/sshd_config
        regexp: "^#?PasswordAuthentication (no|yes)$"
        replace: "PasswordAuthentication no"
      become: true

    - name: Disabling PermitEmptyPasswords
      ansible.builtin.replace:
        path: /etc/ssh/sshd_config
        regexp: "^#?PermitEmptyPasswords (no|yes)$"
        replace: "PermitEmptyPasswords no"
      become: true

    # **NOTE:** Some cloud providers come with subconfig files in sshd_config.d that may override your main
    # configuration, update the list with files you want to remove.
    - name: Removing ssh config files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/ssh/sshd_config.d/50-cloud-init.conf
        - /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
      become: true

    - name: Disabling PermitRootLogin
      ansible.builtin.replace:
        path: /etc/ssh/sshd_config
        regexp: "^#?PermitRootLogin (no|yes|prohibit-password|without-password|forced-commands-only)$"
        replace: "PermitRootLogin no"
      become: true
      when: not (permit_root_login | default(false))

    - name: Restarting ssh service
      ansible.builtin.systemd_service:
        state: restarted
        name: ssh
      become: true
