# **NOTE:** Make sure you have SSH keys set up, otherwise you will not be able to reconnect to the server after this play
- name: Disabling password authentication and empty passwords
  hosts: all

  tasks:
  - name: Disabling PasswordAuthentication
    ansible.builtin.replace:
      path: /etc/ssh/sshd_config
      regexp: '^#?PasswordAuthentication (no|yes)$'
      replace: 'PasswordAuthentication no'
    become: true

  - name: Disabling PermitEmptyPasswords
    ansible.builtin.replace:
      path: /etc/ssh/sshd_config
      regexp: '^#?PermitEmptyPasswords (no|yes)$'
      replace: 'PermitEmptyPasswords no'
    become: true

  - name: Restarting ssh service
    ansible.builtin.systemd_service:
      state: restarted
      name: ssh
    become: true