- name: Enabling firewall with configuration for OpenSSH
  hosts: all

  tasks:
  - name: Allowing access to OpenSSH
    community.general.ufw:
      rule: allow
      name: OpenSSH
    become: true

  - name: Enable UFW and denying traffic to unallowed ports/apps
    community.general.ufw:
      state: enabled
      policy: deny
    become: true