# Provide your host configuration below (see https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html)
# you may also create/append to this file during your CI/CD pipeline steps
# Note that you can specify variables directly inline or in the host_vars directory, using a file i.e. example.com (ini or yml). 
# See the example file in ./host_vars/example.com.yml.
server:
  hosts:
    example.com
