# Provide your host configuration below (see https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html)
# you may also create/append to this file during your CI/CD pipeline steps
# Note that you can specify variables directly inline or in the host_vars directory, using a file i.e. example.com (ini or yml).
# See the example file in ./host_vars/example.com.yml.

# Note: The init_controller will be used to initialize the cluster using `kubeadm init` and as execution target to apply configurations.
# You may choose any other host under controller for this purpose but make sure it's only a single host, as Kubernetes
# will replicate these to the other control planes.
# There is some additional host_var variables to be specified for the used init_controller, which are used to apply
# configurations. See the example.com.yml in the host_vars directory.
# These may be specified for all controllers if you want the flexibility of changing the init_controller, which is
# helpful if your initial init_controller becomes unavailable due to maintenance or an issue.
init_controller:
  hosts:
    example.com:

controller:
  hosts:
    example.com:
    controller0.example.com:
    controller1.example.com:

worker:
  hosts:
    # This will lead to your control plane, since it is defined in the controller list as well, to be "untainted" and
    # a target for the load balancer.
    # This may be a security concern, see also:
    # https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#control-plane-node-isolation
    example.com:
    node0.example.com:
    node1.example.com:
    node2.example.com:
