# Provide your host configuration below (see https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html)
# you may also create/append to this file during your CI/CD pipeline steps
# Note that you can specify variables directly inline or in the host_vars directory, using a file i.e. example.com (ini or yml). 
# See the example file in ./host_vars/example.com.yml.
controller:
  hosts:
    example.com

worker:
  hosts:
    # This will lead to your control plane, since it is defined in the controller list as well, to be "untainted" and a target for the load balancer.
    # This may be a security concern, see also: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#control-plane-node-isolation
    example.com 
    node0.example.com
    node1.example.com
    node2.example.com
