# Docker installation as per official guide (see https://docs.docker.com/engine/install/)
- name: Installing Docker
  hosts: all
  become: true

  tasks:
  - name: Add docker repositories GPG key
    apt_key:
      url: https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg
      state: present

  - name: Add docker repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable
      state: present

  - name: Installing docker community edition
    import_role:
      name: install
    vars:
      packages:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

  - name: Adding current user to group docker
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes

  - name: Start docker service
    service:
      name: docker
      state: started