# containerd installation as per official guide (see https://github.com/containerd/containerd/blob/main/docs/getting-started.md)
- name: Installing containerd
  hosts: all
  become: true

  tasks:
  - name: Adding Docker repositories GPG key
    apt_key:
      url: https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg
      state: present

  - name: Adding Docker repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable
      state: present

  - name: Installing containerd.io
    import_role:
      name: install
    vars:
      packages:
        - containerd.io

  - name: Start containerd service
    service:
      name: containerd
      state: started
      enabled: true