# NOTE: containerd is required to be installed (i.e. using install_docker.yml), but will be configured for use with K8s
- name: Installing K8s using containerd
  hosts: all
  become: true

  roles:
    - k8s

- name: Installing kubectl
  hosts: controller
  become: true

  tasks:
  - name: Installing kubectl
    import_role:
      name: install
    vars:
      packages:
        - kubectl
