# Joining K8s cluster (see https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/)
- name: Generating K8s token and join command
  hosts: controller
  
  tasks:
  - name: Generate join token and store join command
    shell: kubeadm token create --print-join-command
    register: join_cmd

- name: Making worker nodes join the cluster
  hosts: worker

  tasks:
  - name: Check if node is also a control-plane
    set_fact: 
      is_control_plane: groups['controller'] | select('equalto', inventory_hostname) | length > 0

  - name: Allowing pods to be run on control-plane if necessary
    shell: kubectl taint nodes --all node-role.kubernetes.io/control-plane- --validate=ignore
    # only runs if the target is also a control-plane, this is disabled by default for security therefore not recommended,
    # but may be required in a single machine cluster
    when: is_control_plane

  - name: Allowing control-plane to be targed by load-balancer
    shell: kubectl label nodes --all node.kubernetes.io/exclude-from-external-load-balancers- 
    when: is_control_plane

  - name: Joing cluster
    shell: "{{ join_cmd.stdout }}"
    become: true
    # control planes are already part of the cluster as they initialized it so no need to join
    when: not is_control_plane