# Deploying cert manager: https://cert-manager.io/docs/installation/helm/#4-install-cert-manager
- name: Deploying cert-manager
  hosts: init_controller
  vars:
    cluster_issuer_email: admin@example.com
    cluster_issuer_name: letsencrypt-prod
    cluster_issuer_server: https://acme-v02.api.letsencrypt.org/directory

  roles:
  - helm

  tasks:
  - name: Installing/Upgrading cert-manager
    ansible.builtin.shell: |
      helm upgrade --install cert-manager cert-manager \
        --repo https://charts.jetstack.io \
        --namespace cert-manager \
        --create-namespace \
        --set installCRDs=true

  - name: Creating cluster-issuer config using letsencrypt ACME challenge
    ansible.builtin.copy:
      dest: "{{ ansible_env.HOME }}/.kube/cluster-issuer.yml"
      content: |
        apiVersion: cert-manager.io/v1
        kind: ClusterIssuer
        metadata: 
          name: {{ cluster_issuer_name }}
        spec: 
          acme: 
            email: {{ cluster_issuer_email }}
            privateKeySecretRef: 
              name: {{ cluster_issuer_name }}
            server: {{ cluster_issuer_server }}
            solvers:
            - http01:
                ingress:
                  ingressClassName: nginx

  - name: Applying cluster-issuer config
    ansible.builtin.shell: kubectl apply -f {{ ansible_env.HOME }}/.kube/cluster-issuer.yml


