---
# See https://metallb.universe.tf/installation/
- name: Installing MetalLB
  hosts: init_controller
  vars:
    metallb_namespace: metallb-system

  roles:
    - helm

  tasks:
    - name: Get kube-proxy configmap
      kubernetes.core.k8s_info:
        kind: ConfigMap
        name: kube-proxy
        namespace: kube-system
      register: kube_proxy_cm_info

    - name: Update kube-proxy configmap to set strictARP to true
      kubernetes.core.k8s:
        state: present
        definition: >-
          {{ kube_proxy_cm_info.resources[0]
          | combine({'data': kube_proxy_cm_info.resources[0].data
          | combine({'config.conf': (kube_proxy_cm_info.resources[0].data['config.conf']
          | replace('strictARP: false', 'strictARP: true'))})}, recursive=True) }}
      when:
        - kube_proxy_cm_info.resources | length > 0
        - kube_proxy_cm_info.resources[0].data is defined
        - kube_proxy_cm_info.resources[0].data['config.conf'] is defined
        - "'strictARP: false' in kube_proxy_cm_info.resources[0].data['config.conf']"
        # This ensures the task only runs if a change from 'false' to 'true' is needed.
        # The k8s module itself is idempotent if the definition doesn't change.

    - name: Installing/Upgrading MetalLB
      kubernetes.core.helm:
        name: metallb
        chart_repo_url: https://metallb.github.io/metallb
        chart_ref: metallb
        release_namespace: "{{ metallb_namespace }}"
        create_namespace: true
        state: present

    - name: Creating .kube folder
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.kube"
        state: directory
        mode: "0755"

    - name: Configuring MetalLB address pool and advertisement
      ansible.builtin.copy:
        dest: "{{ ansible_env.HOME }}/.kube/metallb.yml"
        mode: "0600"
        content: |
          apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:
            name: public-pool
            namespace: {{ metallb_namespace }}
          spec:
            addresses: {{ metallb_addresses }}
          ---
          apiVersion: metallb.io/v1beta1
          kind: L2Advertisement
          metadata:
            name: public-advertisement
            namespace: {{ metallb_namespace }}
          spec:
            ipAddressPools:
              - public-pool

    - name: Applying MetalLB configuration
      kubernetes.core.k8s:
        state: present
        src: "{{ ansible_env.HOME }}/.kube/metallb.yml"
