---
- name: Deploy kube-prometheus-stack with preconfigured dashboards
  hosts: init_controller
  vars:
    prometheus_namespace: monitoring
    cluster_issuer: letsencrypt-prod
    grafana_hosts:
      - dashboard.example.com
    grafana_service_name: kube-prometheus-stack-grafana
    grafana_service_port: 80
  vars_files:
    - vars/example_user_vault.yml

  roles:
    - helm

  tasks:
    - name: Creating .kube folder
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.kube/monitoring"
        state: directory
        mode: "0755"
      register: dest_folder

    - name: Creating kube-prometheus-stack values file
      ansible.builtin.copy:
        dest: "{{ dest_folder.path }}/prometheus-values.yml"
        mode: "0600"
        content: |
          grafana:
            adminUser: "{{ vault_grafana_user }}"
            adminPassword: "{{ vault_grafana_password }}"
            grafana.ini:
              auth.anonymous:
                enabled: false
            ingress:
              enabled: false
            dashboards:
              default:
                node-exporter-full:
                  gnetId: 1860
                  revision: 41
                  datasource: Prometheus
                k8s-dashboard:
                  gnetId: 15661
                  revision: 2
                  datasource: Prometheus
          prometheus:
            prometheusSpec:
              serviceMonitorSelectorNilUsesHelmValues: false
      register: prometheus_values
      no_log: true

    - name: Deploying kube-prometheus-stack
      kubernetes.core.helm:
        name: kube-prometheus-stack
        chart_repo_url: https://prometheus-community.github.io/helm-charts
        chart_ref: kube-prometheus-stack
        release_namespace: "{{ prometheus_namespace }}"
        create_namespace: true
        state: present
        values_files:
          - "{{ prometheus_values.dest }}"
      no_log: true # Values file contains secrets

    - name: Waiting for Grafana service to be available
      ansible.builtin.command: kubectl get svc -n {{ prometheus_namespace }}
      register: svc_output
      until: '"{{ grafana_service_name }}" in svc_output.stdout'
      retries: 10
      delay: 15

    - name: Deploying grafana ingress
      ansible.builtin.template:
        lstrip_blocks: true
        src: templates/ingress_deployment.j2
        dest: "{{ dest_folder.path }}/ingress.yml"
        mode: "0600"
      vars:
        cluster_issuer_name: "{{ cluster_issuer }}"
        app_name: grafana
        create_deployment: false
        create_service: false
        external_service_name: "{{ grafana_service_name }}"
        external_service_port: "{{ grafana_service_port }}"
        metadata_namespace: "{{ prometheus_namespace }}"
        tls_hosts: "{{ grafana_hosts }}"
      register: ingress

    - name: Applying Grafana ingress
      kubernetes.core.k8s:
        state: present
        src: "{{ ingress.dest }}"
