---
- name: Deploying application to Kubernetes
  hosts: all

  tasks:
    - name: Create namespace if it doesn't exist
      kubernetes.core.k8s:
        name: "{{ app_namespace }}"
        api_version: v1
        kind: Namespace
        state: present

    - name: Create app directory for manifests
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.kube/{{ app_folder }}"
        state: directory
        mode: "0755"
      register: app_dir

    - name: Create dockerconfigjson content for registry authentication
      ansible.builtin.set_fact:
        reg_auth_string: "{{ (registry.username + ':' + registry.password) | b64encode }}"
        reg_secret_name: "{{ app_name }}-regcred"
        reg_pull_secrets:
          - name: "{{ app_name }}-regcred"
      when: registry is defined and registry.host is defined and registry.username is defined and registry.password is defined
      no_log: true

    - name: Build registry auth structure
      ansible.builtin.set_fact:
        reg_auth:
          auths: "{{ {registry.host: {'auth': reg_auth_string}} }}"
      when: reg_auth_string is defined
      no_log: true

    - name: Create container registry secret for authentication
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "{{ reg_secret_name }}"
            namespace: "{{ app_namespace }}"
          type: kubernetes.io/dockerconfigjson
          data:
            .dockerconfigjson: "{{ reg_auth | to_json | b64encode }}"
      when: reg_auth is defined
      no_log: true

    - name: Deploy application manifest
      ansible.builtin.template:
        lstrip_blocks: true
        src: templates/ingress_deployment.j2
        dest: "{{ app_dir.path }}/{{ app_name }}.yml"
        mode: "0600"
      vars:
        metadata_namespace: "{{ app_namespace }}"
        tls_hosts: "{{ app_domains }}"
        image_pull_secrets: "{{ reg_pull_secrets }}"
      register: app_deployment

    - name: Deploying application {{ app_name }}
      kubernetes.core.k8s:
        state: present
        src: "{{ app_deployment.dest }}"
