  # See https://kubernetes.github.io/ingress-nginx/deploy/
- name: Deploying ingress-nginx Controller
  hosts: controller

  tasks:
  - name: Deploying ingress-nginx
    ansible.builtin.shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.0/deploy/static/provider/cloud/deploy.yaml


