- name: OS specific install
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Installing CRI-O
  import_role:
    name: install
  vars:
    packages:
      - cri-o

- name: Starting CRI-O service
  ansible.builtin.systemd_service:
    name: crio.service
    state: started
    enabled: true