- name: OS specific install
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Installing kubectl
  import_role:
    name: install
  vars:
    packages:
      - kubelet
      - kubeadm
      - kubectl
