---
- name: OS specific install
  ansible.builtin.import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Installing kubectl
  ansible.builtin.import_role:
    name: install
  vars:
    install_packages:
      - kubelet=1.33.2
      - kubeadm=1.33.2
