name: CI
on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]

jobs:
  format:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'  # latest LTS version of Node.js
      - name: Installing dependencies
        run: npm ci
      - name: Checking formatting
        run: npm run format:check

  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          args: "-p *.yml"
          setup_python: "true"
          working_directory: "ansible"
          requirements_file: "ansible/requirements.txt"
